# Generated by Django 2.1.7 on 2019-05-01 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_collector', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
