# Generated by Django 2.1.7 on 2019-05-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_collector', '0003_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
