# Generated by Django 2.1.7 on 2019-05-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_collector', '0004_auto_20190503_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='media_url',
        ),
    ]
